# Specify the version for docker-compose.yml
version: "3.8"

# add the serivces needed (postgres,go)
services:
  go:
    container_name: go1
    image: anil2/factorial:1
    # build the Dockerfile, alternatively use an image.
    build:
      context: .
      dockerfile: Dockerfile
    # depends_on:
    #   - "postgres"
    restart: always
    ports:
      - "8002:8000"